name: Build and Publish NuGet Package

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build + Pack
    - name: Pack NuGet package
      run: |
        dotnet pack src/LazyFramework.DX.csproj --configuration Release --output ./artifacts

    # Capture the .nupkg file path
    - name: Get .nupkg file path
      id: get_nupkg_path
      shell: bash
      run: |
        # Capture the full path of the .nupkg file
        PACKAGE_PATH=$(find ./artifacts -name "*.nupkg" | head -n 1)
        echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
        echo "Package path is $PACKAGE_PATH"

    # Publish to NuGet
    - name: Publish to NuGet
      run: |
        echo "Publishing package to NuGet..."
        dotnet nuget push ${{ env.PACKAGE_PATH }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    # Publish to GitHub
    - name: Publish to GitHub
      run: |
        echo "Publishing package to GitHub..."
        dotnet nuget push ${{ env.PACKAGE_PATH }} --api-key ${{ secrets.TOKEN_GITHUB }} --source "https://nuget.pkg.github.com/yashbrahmbhatt/index.json"

    # Optionally, create a GitHub release (this step is currently commented out)
    # - name: Create GitHub Release
    #   uses: actions/github-script@v7
    #   with:
    #     script: |
    #       const packagePath = process.env.PACKAGE_PATH;
    #       const version = packagePath.replace("LazyFramework.DX.","");
    #       
    #       const release = await github.rest.repos.createRelease({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         tag_name: `v${version}`,
    #         name: `Release v${version}`,
    #         body: `Release notes for version ${version}.`,
    #         draft: false,
    #         prerelease: false
    #       });
    #       await github.rest.repos.uploadReleaseAsset({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         release_id: release.data.id,
    #         name: `LazyFramework.DX-${version}.nupkg`,
    #         data: require('fs').createReadStream(packagePath)
    #       });
