name: Build and Publish NuGet Package

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore src/LazyFramework.DX.csproj --source https://api.nuget.org/v3/index.json --source https://pkgs.dev.azure.com/uipath/Public.Feeds/_packaging/UiPath-Official/nuget/v3/index.json

    # Build the project
    - name: Build
      run: dotnet build src/LazyFramework.DX.csproj --configuration Release

    # Pack the project to create a NuGet package
    - name: Pack
      run: dotnet pack src/LazyFramework.DX.csproj --configuration Release --output ./nupkgs

    # Debug - List Packages
    - name: List packages
      run: dir .\nupkgs
    # Publish the NuGet package
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
